### ISSUE TITLE
Incorrect error message (per JSONRPC spec)

### ISSUE THREAD

**Issue by Fedor-sa** [neonlabsorg/neon-proxy.py#74]
### Environment:
BA Proxy 0.1.4
neon-proxy.py:5d90511241d7ad694a675e14af8e0157f1bae4b3
### Steps
Execute one of the tests below
### Observed
Test failed due to `E AssertionError: assert 'invalid parameters' == 'Invalid params'`
Test expects error message = invalid parameters
### Expected
In accordance with [json rpc specification](https://www.jsonrpc.org/specification#error_object) error message has to be `Invalid params`
### Proposed solution
Update tests to expect valid error message
### Tests affected
test_get_logs_negative_params[address-12345-invalid parameters--32602-Method.ETH_GET_LOGS]
test_get_logs_negative_params[topics-Invalid(address,uint256,string,bytes32,bool)-invalid parameters--32602-Method.ETH_GET_LOGS]
test_eth_get_transaction_by_hash_negative
test_get_transaction_receipt_with_incorrect_hash[eth_getTransactionReceipt]
test_eth_get_block_by_hash_with_incorrect_hash[31-False]
test_eth_get_block_by_hash_with_incorrect_hash[bad_hash-True]
est_eth_get_block_by_number_with_incorrect_data

**Comment by afalaleev** [comment]
I've checked different public Ethereum endpoints.
There are many different variants of answers.

So, I've change the logic in neon-tests and neon-proxy to support JSON-RPC spec.

**Comment by afalaleev** [comment]
@Fedor-sa the issue is resolved
