### ISSUE TITLE
Incorrect error code (per JSONRPC spec)

### ISSUE THREAD

**Issue by Fedor-sa** [neonlabsorg/neon-proxy.py#75]
### Environment
BA Proxy 0.1.4
neon-proxy.py:5d90511241d7ad694a675e14af8e0157f1bae4b3
### Steps
- Execute one of the tests below **OR**
- send JSON like below
```
{
	"jsonrpc":"2.0",
	"method":"eth_getLogs",
	"params":[{
		"blockHash": "0x7014643ec7d59b9f3f112870269371ce733db0830f4829b05c15fb184a91edd7",
        "toBlock": "latest"
	}],
	"id":74
}
```
### Observed
Error message
```
{
    "jsonrpc": "2.0",
    "id": 74,
    "error": {
        "code": -32600,
        "message": "invalid filter: if blockHash is supplied fromBlock and toBlock must not be"
    }
}
```
### Expected
According to [JSON RPC specification](https://www.jsonrpc.org/specification#error_object) code 32600 means 
> The JSON sent is not a valid Request object.

whereas this message is correct JSON from syntax point of view
Response message should have code `-32602 Invalid method parameter(s).`
### Proposed solution
Update response with correct code
Update tests to expect correct code
### Affected tests
test_get_logs_blockhash_negative_tags

**Comment by afalaleev** [comment]
@Fedor-sa go-ethereum has a custom realization of JSONRPC, neon-proxy tries to simulate it, not JSONSPEC.

@kristinaNikolaevaa should be rechecked.
The last version of go-ethereum returns another error message:
https://github.com/ethereum/go-ethereum/blob/2e8e35f2ada60e8e90aff8f6374ea7cd7da16116/ethclient/ethclient.go#L465
```
return nil, errors.New("cannot specify both BlockHash and FromBlock/ToBlock")
```
Please recheck the error code too.

**Comment by kristinaNikolaevaa** [comment]
@afalaleev Now geth returns 'invalid argument 0: cannot specify both BlockHash and FromBlock/ToBlock, choose one or the other' and the code is 32602

**Comment by afalaleev** [comment]
@Fedor-sa 
The issue is resolved.
Details are in #74
