### ISSUE TITLE
 Return error message in case of too long block number in eth_getBlockByNumber

### ISSUE THREAD

**Issue by Fedor-sa** [neonlabsorg/neon-proxy.py#83]
### Environment
BA Proxy 0.1.4
neon-proxy.py:5d90511241d7ad694a675e14af8e0157f1bae4b3

### Steps

send JSON like below with too long block number
```
{
    "method":"eth_getBlockByNumber",
    "params":["0x55192d7d9e36433b64f2b9d9309a5c5d36b1561c888dcfa8f31078f000fa7cdd",true],
    "id":1,
    "jsonrpc":"2.0"
}
```

### Observed
Response message
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": null
}
```
### Expected
Response message with code -32602

Tested with _geth 1.14.6_
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32602,
        "message": "invalid argument 0: hex number > 64 bits"
    }
}
```

### Proposed solution
Update response with correct code
Update tests to expect correct code

### Affected tests
block_by_number_with_not_exist_data

**Comment by afalaleev** [comment]
Resolved
